# Generated by Django 5.2.8 on 2025-12-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50, unique=True)),
                ('fingerprint_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('STR_PENDING', 'STR Pending'), ('STR_GENERATED', 'STR Generated'), ('MATCHED', 'Matched')], default='UPLOADED', max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cases.case')),
            ],
        ),
    ]
